name: Install and tests
run-name: Install and tests 🚀
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you need
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build yarn
        run: yarn build
      - name: Unit tests
        run: yarn test
      - name: Integration tests
        run: yarn test:e2e
      - name: Report JUnit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          name: junit-results
          files: |
            reports/*.xml
